"""Initial schema with all models

Revision ID: af041481183c
Revises: 
Create Date: 2025-11-11 02:13:16.843935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af041481183c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('dominant_positions', sa.JSON(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_first_name'), 'players', ['first_name'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('crest_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('organiser', sa.JSON(), nullable=True),
    sa.Column('teams', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_slug'), 'tournaments', ['slug'], unique=True)
    op.create_table('stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage_type', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('tournament_rosters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', 'player_id', name='unique_roster_entry')
    )
    op.create_index(op.f('ix_tournament_rosters_id'), 'tournament_rosters', ['id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('teams', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('pool_id', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.String(), nullable=True),
    sa.Column('field_label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_timeouts', sa.Integer(), nullable=True),
    sa.Column('away_timeouts', sa.Integer(), nullable=True),
    sa.Column('cap_at', sa.Integer(), nullable=True),
    sa.Column('soft_cap_minutes', sa.Integer(), nullable=True),
    sa.Column('hard_cap_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_slug'), 'matches', ['slug'], unique=True)
    op.create_table('match_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('clock_label', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_id'), 'match_events', ['id'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('points_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'tournament_id', 'match_id', name='unique_player_stats')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_match_id'), 'player_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_tournament_id'), 'player_stats', ['tournament_id'], unique=False)
    op.create_table('spirit_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('opponent_team_id', sa.String(), nullable=False),
    sa.Column('rules_knowledge', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('fairness', sa.Integer(), nullable=False),
    sa.Column('positive_attitude', sa.Integer(), nullable=False),
    sa.Column('communication', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='unique_spirit_score')
    )
    op.create_index(op.f('ix_spirit_scores_id'), 'spirit_scores', ['id'], unique=False)
    op.create_index(op.f('ix_spirit_scores_match_id'), 'spirit_scores', ['match_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('holds', sa.Integer(), nullable=True),
    sa.Column('breaks', sa.Integer(), nullable=True),
    sa.Column('offensive_efficiency', sa.Float(), nullable=True),
    sa.Column('possession_percentage', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('pulls', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tournament_id', 'match_id', name='unique_team_stats')
    )
    op.create_index(op.f('ix_team_stats_id'), 'team_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_stats_match_id'), 'team_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_stats_tournament_id'), 'team_stats', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_stats_tournament_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_match_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_spirit_scores_match_id'), table_name='spirit_scores')
    op.drop_index(op.f('ix_spirit_scores_id'), table_name='spirit_scores')
    op.drop_table('spirit_scores')
    op.drop_index(op.f('ix_player_stats_tournament_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_match_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_matches_slug'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_tournament_rosters_id'), table_name='tournament_rosters')
    op.drop_table('tournament_rosters')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_tournaments_slug'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_first_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###

