import type {
  Match,
  MatchEvent,
  Player,
  SeasonSummary,
  SpiritScore,
  Team,
  Tournament,
} from "@/lib/api/schemas";

const nowIso = () => new Date().toISOString();

// Sky This players (based on real roster from scores.frisbee.pl)
const skyThisPlayers: Player[] = [
  {
    id: "player-deskur",
    jerseyNumber: 47,
    name: { first: "Benedykt", last: "Deskur", display: "Benedykt Deskur" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 42,
      totalAssists: 38,
      totalDs: 18,
      totalPointsPlayed: 210,
    },
  },
  {
    id: "player-k-litwinski",
    jerseyNumber: 29,
    name: { first: "Krzysztof", last: "Litwiński", display: "Krzysztof Litwiński" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler", "cutter"],
    throws: "both",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 35,
      totalAssists: 41,
      totalDs: 12,
      totalPointsPlayed: 198,
    },
  },
  {
    id: "player-m-litwinski",
    jerseyNumber: 63,
    name: { first: "Maciej", last: "Litwiński", display: "Maciej Litwiński" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense", "defense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 28,
      totalAssists: 22,
      totalDs: 24,
      totalPointsPlayed: 185,
    },
  },
  {
    id: "player-madej",
    jerseyNumber: 16,
    name: { first: "Zuzanna", last: "Madej", display: "Zuzanna Madej" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["handler"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 31,
      totalAssists: 36,
      totalDs: 14,
      totalPointsPlayed: 192,
    },
  },
  {
    id: "player-szymczak",
    jerseyNumber: 3,
    name: { first: "Kinga", last: "Szymczak", display: "Kinga Szymczak" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 26,
      totalAssists: 18,
      totalDs: 19,
      totalPointsPlayed: 175,
    },
  },
  {
    id: "player-janik",
    jerseyNumber: 20,
    name: { first: "Piotr", last: "Janik", display: "Piotr Janik" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["defense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 18,
      totalAssists: 12,
      totalDs: 28,
      totalPointsPlayed: 168,
    },
  },
  {
    id: "player-lomnicka",
    jerseyNumber: 12,
    name: { first: "Marika", last: "Łomnicka", display: "Marika Łomnicka" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 22,
      totalAssists: 15,
      totalDs: 16,
      totalPointsPlayed: 152,
    },
  },
  {
    id: "player-moszynski",
    jerseyNumber: 7,
    name: { first: "Jan", last: "Moszyński", display: "Jan Moszyński" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["defense"],
    clubHistory: [
      {
        teamId: "team-sky-this",
        teamName: "Sky This",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 15,
      totalAssists: 9,
      totalDs: 31,
      totalPointsPlayed: 145,
    },
  },
];

// 4Hands players (based on real roster from scores.frisbee.pl)
const fourHandsPlayers: Player[] = [
  {
    id: "player-latoszewski",
    jerseyNumber: 31,
    name: { first: "Piotr", last: "Latoszewski", display: "Piotr Latoszewski" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler"],
    throws: "both",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 48,
      totalAssists: 52,
      totalDs: 15,
      totalPointsPlayed: 225,
    },
  },
  {
    id: "player-osiecki",
    jerseyNumber: 16,
    name: { first: "Kamil", last: "Osiecki", display: "Kamil Osiecki" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler", "cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 44,
      totalAssists: 38,
      totalDs: 18,
      totalPointsPlayed: 218,
    },
  },
  {
    id: "player-stanislawska",
    jerseyNumber: 39,
    name: { first: "Dorota", last: "Stanisławska", display: "Dorota Stanisławska" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["handler"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 36,
      totalAssists: 42,
      totalDs: 12,
      totalPointsPlayed: 205,
    },
  },
  {
    id: "player-chlebicka",
    jerseyNumber: 4,
    name: { first: "Grażyna", last: "Chlebicka", display: "Grażyna Chlebicka" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 32,
      totalAssists: 24,
      totalDs: 16,
      totalPointsPlayed: 195,
    },
  },
  {
    id: "player-urbanska",
    jerseyNumber: 5,
    name: { first: "Julia", last: "Urbańska", display: "Julia Urbańska" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense", "defense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 28,
      totalAssists: 19,
      totalDs: 22,
      totalPointsPlayed: 188,
    },
  },
  {
    id: "player-demianiuk",
    jerseyNumber: 22,
    name: { first: "Aleksandra", last: "Demianiuk", display: "Aleksandra Demianiuk" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["defense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 19,
      totalAssists: 14,
      totalDs: 26,
      totalPointsPlayed: 172,
    },
  },
  {
    id: "player-podgajny",
    jerseyNumber: 9,
    name: { first: "Kacper", last: "Podgajny", display: "Kacper Podgajny" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["defense"],
    clubHistory: [
      {
        teamId: "team-4hands",
        teamName: "4Hands",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 16,
      totalAssists: 11,
      totalDs: 29,
      totalPointsPlayed: 165,
    },
  },
];

// Additional teams
const additionalPlayers: Player[] = [
  // Wrocław Panthers
  {
    id: "player-nowak-panthers",
    jerseyNumber: 11,
    name: { first: "Tomasz", last: "Nowak", display: "Tomasz Nowak" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-wroclaw-panthers",
        teamName: "Wrocław Panthers",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 3,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 24,
      totalAssists: 32,
      totalDs: 11,
      totalPointsPlayed: 156,
    },
  },
  {
    id: "player-kowalczyk",
    jerseyNumber: 8,
    name: { first: "Magdalena", last: "Kowalczyk", display: "Magdalena Kowalczyk" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-wroclaw-panthers",
        teamName: "Wrocław Panthers",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 3,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 28,
      totalAssists: 16,
      totalDs: 18,
      totalPointsPlayed: 148,
    },
  },
  // Poznan Hussars
  {
    id: "player-wisniewski",
    jerseyNumber: 14,
    name: { first: "Jakub", last: "Wiśniewski", display: "Jakub Wiśniewski" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler"],
    throws: "both",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-poznan-hussars",
        teamName: "Poznań Hussars",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 4,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 21,
      totalAssists: 28,
      totalDs: 9,
      totalPointsPlayed: 142,
    },
  },
  {
    id: "player-kaminska",
    jerseyNumber: 17,
    name: { first: "Natalia", last: "Kamińska", display: "Natalia Kamińska" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["defense"],
    clubHistory: [
      {
        teamId: "team-poznan-hussars",
        teamName: "Poznań Hussars",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 4,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 18,
      totalAssists: 12,
      totalDs: 24,
      totalPointsPlayed: 138,
    },
  },
  // Kraków Dragons
  {
    id: "player-lewandowski",
    jerseyNumber: 9,
    name: { first: "Michał", last: "Lewandowski", display: "Michał Lewandowski" },
    pronouns: "he/him",
    nationality: "PL",
    roles: ["handler"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-krakow-dragons",
        teamName: "Kraków Dragons",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 5,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 19,
      totalAssists: 25,
      totalDs: 8,
      totalPointsPlayed: 128,
    },
  },
  {
    id: "player-wojcik",
    jerseyNumber: 23,
    name: { first: "Karolina", last: "Wójcik", display: "Karolina Wójcik" },
    pronouns: "she/her",
    nationality: "PL",
    roles: ["cutter"],
    throws: "right",
    dominantPositions: ["offense"],
    clubHistory: [
      {
        teamId: "team-krakow-dragons",
        teamName: "Kraków Dragons",
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 5,
          },
        ],
      },
    ],
    stats: {
      totalGoals: 22,
      totalAssists: 14,
      totalDs: 15,
      totalPointsPlayed: 124,
    },
  },
];

const mockPlayers: Player[] = [
  ...skyThisPlayers,
  ...fourHandsPlayers,
  ...additionalPlayers,
];

const mockTeams: Team[] = [
  {
    id: "team-sky-this",
    name: "Sky This",
    shortName: "Sky",
    slug: "sky-this",
    division: "mixed",
    clubName: "Sky This Ultimate",
    city: "Warsaw",
    country: "PL",
    foundedYear: 2011,
    primaryColor: "#0f172a",
    secondaryColor: "#38bdf8",
    seasons: [
      {
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 2,
            wins: 6,
            losses: 1,
          },
        ],
      },
    ],
    roster: skyThisPlayers.map((player, index) => ({
      tournamentId: "tournament-mpx-2025",
      player,
      jerseyNumber: player.jerseyNumber,
      captain: index === 0,
    })),
  },
  {
    id: "team-4hands",
    name: "4Hands",
    shortName: "4H",
    slug: "4hands",
    division: "mixed",
    clubName: "4Hands Ultimate",
    city: "Wrocław",
    country: "PL",
    foundedYear: 2013,
    primaryColor: "#f97316",
    secondaryColor: "#0f172a",
    seasons: [
      {
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 1,
            wins: 7,
            losses: 0,
          },
        ],
      },
    ],
    roster: fourHandsPlayers.map((player, index) => ({
      tournamentId: "tournament-mpx-2025",
      player,
      jerseyNumber: player.jerseyNumber,
      captain: index === 0,
    })),
  },
  {
    id: "team-wroclaw-panthers",
    name: "Wrocław Panthers",
    shortName: "Panthers",
    slug: "wroclaw-panthers",
    division: "mixed",
    clubName: "Wrocław Panthers Ultimate",
    city: "Wrocław",
    country: "PL",
    foundedYear: 2015,
    primaryColor: "#8b5cf6",
    secondaryColor: "#fbbf24",
    seasons: [
      {
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 3,
            wins: 5,
            losses: 2,
          },
        ],
      },
    ],
    roster: additionalPlayers
      .filter((p) => p.clubHistory[0].teamId === "team-wroclaw-panthers")
      .map((player, index) => ({
        tournamentId: "tournament-mpx-2025",
        player,
        jerseyNumber: player.jerseyNumber,
        captain: index === 0,
      })),
  },
  {
    id: "team-poznan-hussars",
    name: "Poznań Hussars",
    shortName: "Hussars",
    slug: "poznan-hussars",
    division: "mixed",
    clubName: "Poznań Hussars Ultimate",
    city: "Poznań",
    country: "PL",
    foundedYear: 2014,
    primaryColor: "#dc2626",
    secondaryColor: "#fef3c7",
    seasons: [
      {
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 4,
            wins: 4,
            losses: 3,
          },
        ],
      },
    ],
    roster: additionalPlayers
      .filter((p) => p.clubHistory[0].teamId === "team-poznan-hussars")
      .map((player, index) => ({
        tournamentId: "tournament-mpx-2025",
        player,
        jerseyNumber: player.jerseyNumber,
        captain: index === 0,
      })),
  },
  {
    id: "team-krakow-dragons",
    name: "Kraków Dragons",
    shortName: "Dragons",
    slug: "krakow-dragons",
    division: "mixed",
    clubName: "Kraków Dragons Ultimate",
    city: "Kraków",
    country: "PL",
    foundedYear: 2016,
    primaryColor: "#059669",
    secondaryColor: "#fde047",
    seasons: [
      {
        season: "2025",
        division: "mixed",
        tournaments: [
          {
            tournamentId: "tournament-mpx-2025",
            tournamentName: "Mistrzostwa Polski Mixed 2025",
            placement: 5,
            wins: 3,
            losses: 4,
          },
        ],
      },
    ],
    roster: additionalPlayers
      .filter((p) => p.clubHistory[0].teamId === "team-krakow-dragons")
      .map((player, index) => ({
        tournamentId: "tournament-mpx-2025",
        player,
        jerseyNumber: player.jerseyNumber,
        captain: index === 0,
      })),
  },
];

// Detailed match events based on the real match from scores.frisbee.pl
const mockMatchEvents: MatchEvent[] = [
  {
    id: "event-1",
    type: "goal",
    sequence: 1,
    point: 1,
    elapsedSeconds: 89,
    clockLabel: "1:29",
    teamId: "team-sky-this",
    summary: "Madej assists Litwiński for the opening goal",
    createdAt: nowIso(),
    scorerId: "player-m-litwinski",
    assisterId: "player-madej",
    offensiveLine: ["player-madej", "player-m-litwinski", "player-deskur"],
  } as MatchEvent,
  {
    id: "event-2",
    type: "goal",
    sequence: 2,
    point: 1,
    elapsedSeconds: 180,
    clockLabel: "3:00",
    teamId: "team-4hands",
    summary: "Podgajny to Osiecki for the quick response",
    createdAt: nowIso(),
    scorerId: "player-osiecki",
    assisterId: "player-podgajny",
    offensiveLine: ["player-podgajny", "player-osiecki", "player-latoszewski"],
  } as MatchEvent,
  {
    id: "event-3",
    type: "goal",
    sequence: 3,
    point: 2,
    elapsedSeconds: 362,
    clockLabel: "6:02",
    teamId: "team-sky-this",
    summary: "Deskur finds Madej in the endzone",
    createdAt: nowIso(),
    scorerId: "player-madej",
    assisterId: "player-deskur",
    offensiveLine: ["player-deskur", "player-madej", "player-k-litwinski"],
  } as MatchEvent,
  {
    id: "event-4",
    type: "turnover",
    sequence: 4,
    point: 2,
    elapsedSeconds: 506,
    clockLabel: "8:26",
    teamId: "team-4hands",
    summary: "Throwaway under pressure",
    createdAt: nowIso(),
    turnoverType: "throwaway",
    causedById: null,
    reason: "Throwaway",
  } as MatchEvent,
  {
    id: "event-5",
    type: "goal",
    sequence: 5,
    point: 2,
    elapsedSeconds: 790,
    clockLabel: "13:10",
    teamId: "team-4hands",
    summary: "Latoszewski to Stanisławska for the break",
    createdAt: nowIso(),
    scorerId: "player-stanislawska",
    assisterId: "player-latoszewski",
    offensiveLine: ["player-latoszewski", "player-stanislawska", "player-chlebicka"],
  } as MatchEvent,
  {
    id: "event-6",
    type: "turnover",
    sequence: 6,
    point: 3,
    elapsedSeconds: 943,
    clockLabel: "15:43",
    teamId: "team-sky-this",
    summary: "Layout block by Janik",
    createdAt: nowIso(),
    turnoverType: "block",
    causedById: "player-janik",
    reason: "Layout block",
  } as MatchEvent,
  {
    id: "event-7",
    type: "goal",
    sequence: 7,
    point: 4,
    elapsedSeconds: 1120,
    clockLabel: "18:40",
    teamId: "team-sky-this",
    summary: "Vlasenko scores off Janik assist",
    createdAt: nowIso(),
    scorerId: "player-deskur",
    assisterId: "player-janik",
    offensiveLine: ["player-janik", "player-deskur", "player-moszynski"],
  } as MatchEvent,
  {
    id: "event-8",
    type: "turnover",
    sequence: 8,
    point: 4,
    elapsedSeconds: 1217,
    clockLabel: "20:17",
    teamId: "team-4hands",
    summary: "Drop in the endzone",
    createdAt: nowIso(),
    turnoverType: "drop",
    causedById: null,
    reason: "Drop",
  } as MatchEvent,
  {
    id: "event-9",
    type: "goal",
    sequence: 9,
    point: 4,
    elapsedSeconds: 1418,
    clockLabel: "23:38",
    teamId: "team-4hands",
    summary: "Latoszewski to Chlebicka",
    createdAt: nowIso(),
    scorerId: "player-chlebicka",
    assisterId: "player-latoszewski",
    offensiveLine: ["player-latoszewski", "player-chlebicka", "player-osiecki"],
  } as MatchEvent,
  {
    id: "event-10",
    type: "timeout",
    sequence: 10,
    point: 5,
    elapsedSeconds: 1528,
    clockLabel: "25:28",
    teamId: "team-4hands",
    summary: "Team timeout called",
    createdAt: nowIso(),
    timeoutType: "team",
  } as MatchEvent,
  {
    id: "event-11",
    type: "goal",
    sequence: 11,
    point: 6,
    elapsedSeconds: 1833,
    clockLabel: "30:33",
    teamId: "team-sky-this",
    summary: "Deskur assists Niesłuchowska",
    createdAt: nowIso(),
    scorerId: "player-szymczak",
    assisterId: "player-deskur",
    offensiveLine: ["player-deskur", "player-szymczak", "player-madej"],
  } as MatchEvent,
  {
    id: "event-12",
    type: "goal",
    sequence: 12,
    point: 7,
    elapsedSeconds: 2161,
    clockLabel: "36:01",
    teamId: "team-sky-this",
    summary: "Szymczak scores off Deskur assist",
    createdAt: nowIso(),
    scorerId: "player-szymczak",
    assisterId: "player-deskur",
    offensiveLine: ["player-deskur", "player-szymczak", "player-k-litwinski"],
  } as MatchEvent,
  {
    id: "event-13",
    type: "period",
    sequence: 13,
    point: 7,
    elapsedSeconds: 2250,
    clockLabel: "37:30",
    teamId: null,
    summary: "Halftime",
    createdAt: nowIso(),
    label: "Halftime",
  } as MatchEvent,
  {
    id: "event-14",
    type: "turnover",
    sequence: 14,
    point: 7,
    elapsedSeconds: 2539,
    clockLabel: "42:19",
    teamId: "team-sky-this",
    summary: "Block forces turnover",
    createdAt: nowIso(),
    turnoverType: "block",
    causedById: "player-urbanska",
    reason: "Block",
  } as MatchEvent,
  {
    id: "event-15",
    type: "goal",
    sequence: 15,
    point: 7,
    elapsedSeconds: 2626,
    clockLabel: "43:46",
    teamId: "team-sky-this",
    summary: "Deskur to Litwiński",
    createdAt: nowIso(),
    scorerId: "player-m-litwinski",
    assisterId: "player-deskur",
    offensiveLine: ["player-deskur", "player-m-litwinski", "player-madej"],
  } as MatchEvent,
  {
    id: "event-16",
    type: "goal",
    sequence: 16,
    point: 8,
    elapsedSeconds: 2744,
    clockLabel: "45:44",
    teamId: "team-4hands",
    summary: "Chlebicka to Stanisławska",
    createdAt: nowIso(),
    scorerId: "player-stanislawska",
    assisterId: "player-chlebicka",
    offensiveLine: ["player-chlebicka", "player-stanislawska", "player-latoszewski"],
  } as MatchEvent,
  {
    id: "event-17",
    type: "goal",
    sequence: 17,
    point: 9,
    elapsedSeconds: 2964,
    clockLabel: "49:24",
    teamId: "team-sky-this",
    summary: "Litwiński finds Moszyński",
    createdAt: nowIso(),
    scorerId: "player-moszynski",
    assisterId: "player-k-litwinski",
    offensiveLine: ["player-k-litwinski", "player-moszynski", "player-deskur"],
  } as MatchEvent,
  {
    id: "event-18",
    type: "goal",
    sequence: 18,
    point: 10,
    elapsedSeconds: 3066,
    clockLabel: "51:06",
    teamId: "team-sky-this",
    summary: "Szymczak scores off Deskur assist",
    createdAt: nowIso(),
    scorerId: "player-szymczak",
    assisterId: "player-deskur",
    offensiveLine: ["player-deskur", "player-szymczak", "player-madej"],
  } as MatchEvent,
  {
    id: "event-19",
    type: "goal",
    sequence: 19,
    point: 10,
    elapsedSeconds: 3193,
    clockLabel: "53:13",
    teamId: "team-4hands",
    summary: "Latoszewski to Stanisławska",
    createdAt: nowIso(),
    scorerId: "player-stanislawska",
    assisterId: "player-latoszewski",
    offensiveLine: ["player-latoszewski", "player-stanislawska", "player-osiecki"],
  } as MatchEvent,
  {
    id: "event-20",
    type: "goal",
    sequence: 20,
    point: 11,
    elapsedSeconds: 3313,
    clockLabel: "55:13",
    teamId: "team-sky-this",
    summary: "Litwiński to Łomnicka",
    createdAt: nowIso(),
    scorerId: "player-lomnicka",
    assisterId: "player-k-litwinski",
    offensiveLine: ["player-k-litwinski", "player-lomnicka", "player-deskur"],
  } as MatchEvent,
  {
    id: "event-21",
    type: "goal",
    sequence: 21,
    point: 11,
    elapsedSeconds: 3501,
    clockLabel: "58:21",
    teamId: "team-4hands",
    summary: "Latoszewski to Osiecki",
    createdAt: nowIso(),
    scorerId: "player-osiecki",
    assisterId: "player-latoszewski",
    offensiveLine: ["player-latoszewski", "player-osiecki", "player-chlebicka"],
  } as MatchEvent,
  {
    id: "event-22",
    type: "goal",
    sequence: 22,
    point: 11,
    elapsedSeconds: 3621,
    clockLabel: "60:21",
    teamId: "team-4hands",
    summary: "Urbańska to Demianiuk",
    createdAt: nowIso(),
    scorerId: "player-urbanska",
    assisterId: "player-demianiuk",
    offensiveLine: ["player-demianiuk", "player-urbanska", "player-stanislawska"],
  } as MatchEvent,
  {
    id: "event-23",
    type: "goal",
    sequence: 23,
    point: 12,
    elapsedSeconds: 3953,
    clockLabel: "65:53",
    teamId: "team-sky-this",
    summary: "Callahan by Litwiński!",
    createdAt: nowIso(),
    scorerId: "player-k-litwinski",
    assisterId: null,
    offensiveLine: ["player-k-litwinski", "player-deskur", "player-madej"],
  } as MatchEvent,
  {
    id: "event-24",
    type: "goal",
    sequence: 24,
    point: 12,
    elapsedSeconds: 4176,
    clockLabel: "69:36",
    teamId: "team-4hands",
    summary: "Chlebicka to Osiecki",
    createdAt: nowIso(),
    scorerId: "player-osiecki",
    assisterId: "player-chlebicka",
    offensiveLine: ["player-chlebicka", "player-osiecki", "player-latoszewski"],
  } as MatchEvent,
  {
    id: "event-25",
    type: "goal",
    sequence: 25,
    point: 13,
    elapsedSeconds: 4444,
    clockLabel: "74:04",
    teamId: "team-sky-this",
    summary: "Litwiński to Deskur for the final point",
    createdAt: nowIso(),
    scorerId: "player-deskur",
    assisterId: "player-k-litwinski",
    offensiveLine: ["player-k-litwinski", "player-deskur", "player-madej"],
  } as MatchEvent,
];

const mockMatches: Match[] = [
  {
    id: "match-4hands-sky-this-final",
    slug: "match-4hands-sky-this-final",
    tournamentId: "tournament-mpx-2025",
    poolId: null,
    division: "mixed",
    round: "Final - O miejsca 1-4",
    startTime: "2025-09-14T09:40:00+02:00",
    endTime: "2025-09-14T11:04:00+02:00",
    fieldId: "field-1",
    fieldLabel: "Field 1",
    status: "final",
    home: {
      teamId: "team-sky-this",
      score: 13,
      timeoutsRemaining: 0,
      spiritScore: null,
    },
    away: {
      teamId: "team-4hands",
      score: 10,
      timeoutsRemaining: 0,
      spiritScore: null,
    },
    events: mockMatchEvents,
    officials: [
      { name: { first: "Tytus", last: "", display: "Tytus" }, role: "scorekeeper" },
      { name: { first: "Miki", last: "", display: "Miki" }, role: "scorekeeper" },
    ],
  },
];

// Extract match without events for tournament schedule display
// const {
//   events: _ignoredEvents,
//   ...mockMatchWithoutEvents
// } = mockMatches[0];
// void _ignoredEvents;

const mockSpiritScores: SpiritScore[] = [
  {
    matchId: "match-4hands-sky-this-final",
    teamId: "team-sky-this",
    opponentTeamId: "team-4hands",
    rubric: {
      rulesKnowledge: 2,
      fouls: 2,
      fairness: 2,
      positiveAttitude: 3,
      communication: 2,
    },
    total: 11,
    notes: "Great spirit throughout the match.",
  },
  {
    matchId: "match-4hands-sky-this-final",
    teamId: "team-4hands",
    opponentTeamId: "team-sky-this",
    rubric: {
      rulesKnowledge: 2,
      fouls: 2,
      fairness: 2,
      positiveAttitude: 2,
      communication: 2,
    },
    total: 10,
    notes: "Competitive but fair game.",
  },
];

const mockTournaments: Tournament[] = [
  {
    id: "tournament-mpx-2025",
    slug: "mpx-2025",
    name: "Mistrzostwa Polski Mixed 2025",
    season: "2025",
    division: "mixed",
    startDate: "2025-09-13",
    endDate: "2025-09-14",
    status: "completed",
    organiser: {
      name: "Polskie Stowarzyszenie Graczy Ultimate",
      website: "https://frisbee.pl",
      contactEmail: "scores@frisbee.pl",
    },
    venue: {
      name: "Central Fields",
      city: "Warsaw",
      country: "PL",
      latitude: 52.2297,
      longitude: 21.0122,
      timezone: "Europe/Warsaw",
      address: "Warsaw Sports Complex, Poland",
      fields: [
        { id: "field-1", label: "Field 1" },
        { id: "field-2", label: "Field 2" },
        { id: "field-3", label: "Field 3" },
      ],
    },
    teams: [
      { teamId: "team-4hands", seed: 1 },
      { teamId: "team-sky-this", seed: 2 },
      { teamId: "team-wroclaw-panthers", seed: 3 },
      { teamId: "team-poznan-hussars", seed: 4 },
      { teamId: "team-krakow-dragons", seed: 5 },
    ],
    stages: [
      {
        id: "stage-mpx-finals",
        name: "O miejsca 1-4",
        stageType: "bracket",
        division: "mixed",
        pools: [
          {
            id: "pool-finals",
            label: "Finals",
            stageId: "stage-mpx-finals",
            teams: [
              { teamId: "team-sky-this", seed: 1 },
              { teamId: "team-4hands", seed: 2 },
            ],
            standings: [
          {
            teamId: "team-sky-this",
            rank: 1,
            wins: 7,
            losses: 0,
            pointsFor: 98,
            pointsAgainst: 65,
            pointDiff: 33,
            spiritAverage: 4.8,
            streak: "W7",
          },
          {
            teamId: "team-4hands",
            rank: 2,
            wins: 6,
            losses: 1,
            pointsFor: 91,
            pointsAgainst: 78,
            pointDiff: 13,
            spiritAverage: 4.5,
            streak: "L1",
          },
          {
            teamId: "team-wroclaw-panthers",
            rank: 3,
            wins: 5,
            losses: 2,
            pointsFor: 84,
            pointsAgainst: 72,
            pointDiff: 12,
            spiritAverage: 4.6,
            streak: "W2",
          },
          {
            teamId: "team-poznan-hussars",
            rank: 4,
            wins: 4,
            losses: 3,
            pointsFor: 76,
            pointsAgainst: 78,
            pointDiff: -2,
            spiritAverage: 4.4,
            streak: "L1",
          },
          {
            teamId: "team-krakow-dragons",
            rank: 5,
            wins: 3,
            losses: 4,
            pointsFor: 68,
            pointsAgainst: 82,
            pointDiff: -14,
            spiritAverage: 4.3,
            streak: "L2",
          },
        ],
          },
        ],
      },
    ],
    standings: [],
    updatedAt: nowIso(),
  },
];

const mockSeasons: SeasonSummary[] = [
  {
    id: "season-2025",
    label: "Season 2025",
    year: 2025,
    divisions: ["mixed", "open", "women"],
    tournaments: [
      {
        id: "tournament-mpx-2025",
        slug: "mpx-2025",
        name: "Mistrzostwa Polski Mixed 2025",
        division: "mixed",
        startDate: "2025-09-13",
        endDate: "2025-09-14",
        status: "completed",
      },
    ],
  },
];

export const mockData = {
  seasons: mockSeasons,
  tournaments: mockTournaments,
  teams: mockTeams,
  players: mockPlayers,
  matches: mockMatches,
  matchEvents: mockMatchEvents,
  spiritScores: mockSpiritScores,
};
